//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Dapper;
using System.Linq;
using DataAccessLayer.Models;
using System.Collections.Generic;

namespace DataAccessLayer.Repositories
{
	public class ChannelRepository:BaseRepository,IChannelRepository
	{
		public ChannelRepository ()
		{
		}

		#region IChannelRepository implementation

		public Channel Insert (Channel channel)
		{
			using (var conn=OpenConnection()) {
				channel.Id=conn.Query<int>(""+SelectIdentityCommand,channel).Single();
			}

			return channel;
		}

		public int Delete (int key)
		{
			throw new NotImplementedException ();
		}

		public int Update (Channel channel)
		{
			throw new NotImplementedException ();
		}

		public DataAccessLayer.Models.Channel Find (int key)
		{
			throw new NotImplementedException ();
		}

		public IEnumerable<DataAccessLayer.Models.Channel> All ()
		{
			throw new NotImplementedException ();
		}

		#endregion

	}
}

