//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DataAccessLayer.Models;
using System.Collections.Generic;
namespace DataAccessLayer.Repositories
{
	/// <summary>
	/// 频道信息存储接口
	/// </summary>
	public interface IChannelRepository
	{
		Channel Insert(Channel channel);
		int Delete(int key);
		int Update(Channel channel);

		Channel Find(int key);
		IEnumerable<Channel> All();
	}
}

